name: node-docs-check

on:
  push:
    branches: [master]
    paths-ignore:
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
  pull_request:
    branches: [master]
    paths-ignore:
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: crates/node-litesvm/yarn.lock
      - name: Install dependencies
        working-directory: crates/node-litesvm
        run: yarn install
      - name: Build with VitePress
        working-directory: crates/node-litesvm
        run: yarn predocs && yarn docs:build
